#!/bin/sh
#
# OpenIPC factoryinit startup script
#

case "$1" in
    start)
        echo -n "Starting factoryinit service: "
        killall -9 socat 2>/dev/null
        killall -9 ipc_server 2>/dev/null
        /usr/bin/ipc_server > /dev/null 2>&1 &
        echo "OK"
        ;;
    stop)
        echo -n "Stopping factoryinit service: "
        killall ipc_server
        echo "OK"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
