#!/bin/sh

APP_HOME=$(CDPATH= cd "$(dirname "$0")" && pwd)
INSTALL_TARGET="/root/encoder"

PROJECT_TITLE="GK7205 Encoder Full Script Controller"
CONFIG_PAGE_TITLE="GK7205 Encoder Config Page"
DELETE_PAGE_TITLE="GK7205 Encoder Delete Page"

DEVICE_ID_SOURCE="missing"
DEVICE_ID_CONFIGURED="false"
DEVICE_ID_DEFAULT="ENC_20260420_001"
CONFIG_PROCESS_ENCODER_DEVICE_ID="${ENCODER_DEVICE_ID:-}"

if [ -n "$CONFIG_PROCESS_ENCODER_DEVICE_ID" ]; then
    DEVICE_ID="$CONFIG_PROCESS_ENCODER_DEVICE_ID"
    DEVICE_ID_SOURCE="global-env:ENCODER_DEVICE_ID"
else
    DEVICE_ID="$DEVICE_ID_DEFAULT"
    DEVICE_ID_SOURCE="config:DEVICE_ID_DEFAULT"
fi

if [ -n "$DEVICE_ID" ]; then
    DEVICE_ID_CONFIGURED="true"
    export DEVICE_ID
    export ENCODER_DEVICE_ID="$DEVICE_ID"
fi

unset CONFIG_PROCESS_ENCODER_DEVICE_ID
DEVICE_VERSION="V-0.0"

MQTT_HOST="123.60.51.11"
MQTT_PORT="1883"
MQTT_USER="mqttadmin"
MQTT_PASS="skilljudge123"
MQTT_QOS="2"

MQTT_SUBSCRIBE_TOPIC="+/+/encoder/${DEVICE_ID}/#"
MQTT_REGISTER_TOPIC="encoder/${DEVICE_ID}/ctrlsrv/0/heartbeat/register"
MQTT_REGISTER_ACK_TOPIC="ctrlsrv/0/encoder/${DEVICE_ID}/heartbeat/register_ack"
MQTT_HEARTBEAT_TOPIC="encoder/${DEVICE_ID}/ctrlsrv/0/heartbeat/heartbeat"
MQTT_HEARTBEAT_ACK_TOPIC="ctrlsrv/0/encoder/${DEVICE_ID}/heartbeat/heartbeat_ack"

HEARTBEAT_INTERVAL_SEC="30"
REGISTER_ACK_TIMEOUT_SEC="10"
REGISTER_RETRY_INTERVAL_SEC="5"
SEGMENT_SCAN_INTERVAL_SEC="10"
SEGMENT_STABLE_SEC="20"
RECORD_FINALIZE_WAIT_SEC="3"
CURL_CONNECT_TIMEOUT_SEC="10"
CURL_UPLOAD_MAX_TIME_SEC="60"
RECORD_FILE_TIME_FORMAT="%Y%m%d%H%M%S"
RECORD_FILE_NAME_TEMPLATE="{device_id}-{task_id}-{timestamp}-{segment_no}.mp4"
RECORD_PATH="/mnt/mmcblk0p1/%F"
RECORD_SPLIT="1"
RECORD_MAX_USAGE="95"
RECORD_SUBSTREAM="false"
RECORD_REMOTE_ROOT="upload"

MAIN_STREAM_ENABLED="true"
MAIN_STREAM_CODEC="h264"
MAIN_STREAM_SIZE="1920x1080"
MAIN_STREAM_FPS="10"
MAIN_STREAM_BITRATE=""
SUB_STREAM_ENABLED="true"
SUB_STREAM_CODEC="h264"
SUB_STREAM_SIZE="640x360"
SUB_STREAM_FPS="15"
SUB_STREAM_BITRATE=""

FTP_HOST="123.60.51.11"
FTP_PORT="21"
FTP_USER="ftpuser"
FTP_PASS="skilljudge123"

SRS_HOST="123.60.51.11"
SRS_PORT="1935"
SRS_APP="live"
SRS_STREAM_PREFIX="stream_${DEVICE_ID}"
STREAM_PUSH_URL=""
STREAM_SUBSTREAM="true"

CAPTURE_SNAPSHOT_URL="http://127.0.0.1/image.jpg"
CAPTURE_LOCAL_DIR="${APP_HOME}/media/capture"
AUDIO_LOCAL_DIR="${APP_HOME}/media/audio"
RECORD_SEARCH_ROOT="/mnt/mmcblk0p1"

STREAM_CONFIG_FILE="/etc/majestic.yaml"
STREAM_CONFIG_BACKUP="/etc/majestic.yaml.encoder.bak"
STREAM_RELOAD_CMD="killall -HUP majestic"
LOG_VERBOSE="false"
CONFIG_COMMAND_VERBOSE="false"
MQTT_PAYLOAD_VERBOSE="false"
HEARTBEAT_LOG_VERBOSE="false"

WORKDIR="${APP_HOME}/runtime"
STATE_DIR="${WORKDIR}/state"
LOG_DIR="${WORKDIR}/logs"
TMP_DIR="${WORKDIR}/tmp"
RECORD_NAMED_LOCAL_DIR="${WORKDIR}/named_records"
LOGFILE="${LOG_DIR}/encoder.log"
MSGID_FILE="${STATE_DIR}/msgid"
TIME_OFFSET_FILE="${STATE_DIR}/time_offset_ms"
SERVER_TIMESTAMP_FILE="${STATE_DIR}/server_timestamp_ms"
RUNTIME_FTP_HOST_FILE="${STATE_DIR}/runtime_ftp_host"
RUNTIME_FTP_PORT_FILE="${STATE_DIR}/runtime_ftp_port"
RUNTIME_FTP_USER_FILE="${STATE_DIR}/runtime_ftp_user"
RUNTIME_FTP_PASS_FILE="${STATE_DIR}/runtime_ftp_pass"
RUNTIME_SRS_HOST_FILE="${STATE_DIR}/runtime_srs_host"
RUNTIME_SRS_PORT_FILE="${STATE_DIR}/runtime_srs_port"
RUNTIME_SRS_USER_FILE="${STATE_DIR}/runtime_srs_user"
RUNTIME_SRS_PASS_FILE="${STATE_DIR}/runtime_srs_pass"

MAIN_PID_FILE="${STATE_DIR}/encoder_main.pid"
LISTENER_PID_FILE="${STATE_DIR}/listener.pid"
HEARTBEAT_PID_FILE="${STATE_DIR}/heartbeat.pid"
SEGMENT_WORKER_PID_FILE="${STATE_DIR}/segment_worker.pid"

STATE_IDLE_FILE="${STATE_DIR}/is_idle"
STATE_RECORDING_FILE="${STATE_DIR}/is_recording"
STATE_PUBLISHING_FILE="${STATE_DIR}/is_publishing"
STATE_CHARGING_FILE="${STATE_DIR}/is_charging"
STATE_BATTERY_FILE="${STATE_DIR}/battery"
STATE_SIGNAL_FILE="${STATE_DIR}/signal"
STATE_CURRENT_TASK_ID_FILE="${STATE_DIR}/current_task_id"
STATE_CURRENT_RECORD_ID_FILE="${STATE_DIR}/current_record_id"
STATE_CURRENT_RECORD_FLOW_FILE="${STATE_DIR}/current_record_flow"
STATE_CURRENT_STREAM_URL_FILE="${STATE_DIR}/current_stream_url"
STATE_RECORD_START_TS_FILE="${STATE_DIR}/record_start_ts"
STATE_RECORD_SESSION_TIME_FILE="${STATE_DIR}/record_session_time"
STATE_SEGMENT_NO_FILE="${STATE_DIR}/segment_no"
STATE_SEGMENT_MANIFEST_FILE="${STATE_DIR}/segment_manifest"

CONFIG_EDITABLE_KEYS="
MQTT_HOST
MQTT_PORT
MQTT_USER
MQTT_PASS
MQTT_QOS
HEARTBEAT_INTERVAL_SEC
REGISTER_ACK_TIMEOUT_SEC
REGISTER_RETRY_INTERVAL_SEC
SEGMENT_SCAN_INTERVAL_SEC
SEGMENT_STABLE_SEC
RECORD_FINALIZE_WAIT_SEC
CURL_CONNECT_TIMEOUT_SEC
CURL_UPLOAD_MAX_TIME_SEC
RECORD_FILE_TIME_FORMAT
RECORD_FILE_NAME_TEMPLATE
RECORD_PATH
RECORD_SPLIT
RECORD_MAX_USAGE
RECORD_SUBSTREAM
RECORD_REMOTE_ROOT
MAIN_STREAM_ENABLED
MAIN_STREAM_CODEC
MAIN_STREAM_SIZE
MAIN_STREAM_FPS
MAIN_STREAM_BITRATE
SUB_STREAM_ENABLED
SUB_STREAM_CODEC
SUB_STREAM_SIZE
SUB_STREAM_FPS
SUB_STREAM_BITRATE
FTP_HOST
FTP_PORT
FTP_USER
FTP_PASS
SRS_HOST
SRS_PORT
SRS_APP
SRS_STREAM_PREFIX
STREAM_PUSH_URL
STREAM_SUBSTREAM
CAPTURE_SNAPSHOT_URL
CAPTURE_LOCAL_DIR
AUDIO_LOCAL_DIR
RECORD_SEARCH_ROOT
STREAM_CONFIG_FILE
STREAM_CONFIG_BACKUP
STREAM_RELOAD_CMD
LOG_VERBOSE
CONFIG_COMMAND_VERBOSE
MQTT_PAYLOAD_VERBOSE
HEARTBEAT_LOG_VERBOSE
"
